2017-03-02 00:59 UTC Viktor Szakats (vszakats users.noreply.github.com)   * utils/hbmk2/hbmk2.prg     ! fix C compiler version detection regression in 2017-02-28 12:57 UTC
  * contrib/hbnetio/utils/hbnetio/hbnetio.prg
    ! fix regression after 3fcdbfba16c1211ec26dd39058074ad01b669e0c

  * contrib/hbformat/utils/hbformat.hbp
    ! always build in shared mode on mac to workaround this sort of error:
      ```
      $ hbformat test.prg
      dyld: Symbol not found: _HB_FUN_HBCLASS
        Referenced from: ~/hb/bin/darwin/clang/../../../lib/darwin/clang/libhbformat.dylib
        Expected in: flat namespace
       in ~/hb/bin/darwin/clang/../../../lib/darwin/clang/libhbformat.dylib
      Abort trap: 6
      ```