2017-08-04 12:45 UTC Viktor Szakats (vszakats users.noreply.github.com)   * src/3rd/pcre/Makefile   * src/3rd/pcre2/Makefile     * replace -sdl- option with -w1* options to downgrade security       errors to warnings in 3rd party code. There was just a single       warning (tested with pcre 1 only, version 8.41) which was       reported upstream, awaiting moderation.
  * src/3rd/zlib/Makefile
    ! fix MSVC -sdl errors by adding option -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP:
        error C4996: '{open|read|write|close}': The POSIX name for this item is deprecated.
        Instead, use the ISO C and C++ conformant name: _{open|read|write|close}.
        See online help for details.
    ! silence remaining MSVC -sdl errors by adding -D_CRT_SECURE_NO_WARNINGS,
      till these get an upstream fix.
    * after above it's possible to drop -sdl- option and warning below that
      came with it:
        cl : Command line warning D9025 : overriding '/sdl' with '/sdl-'